theme: jekyll-theme-minimal
title: ClassConnect
description: Manual de usuario

# Navegaci√≥n personalizada
navigation:
  - name: "Manual de usuario App Mobile"
    url: "/"
  - name: "Manual de usuario Backoffice"
    url: "/Backoffice"